# Generated by Django 6.0.6 on 2026-06-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideevent',
            old_name='id_event',
            new_name='id_ride_event',
        ),
    ]
