# Generated by Django 6.0.6 on 2026-06-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_pickup_time_alter_ride_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
